import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">CarFinder!</a>
        </h1>

        <div className={styles.grid}>

          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Find Cars &#10148;</h2>
            <p>Find in-depth information about cars and other local vehicles.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Compare Cars &#10148;</h2>
            <p>Compare and learn about different models of cars or just look around!</p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://replit.com/@codertezz1/PointedBestRectangle"
          target="_blank"
          rel="noopener noreferrer"
        >
          Next.js on Replit
        </a>
      </footer>
    </div>
  )
}
